---

- name: install prerquisites
  apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
  vars:
      packages:
          - curl
          - gnupg2
          - ca-certificates
          - lsb-release
  become: yes
  tags: install

- name: prepare nginx package
  command: echo "deb http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" | sudo tee /etc/apt/sources.list.d/nginx.list
  become: yes
- name: add signature
  command: "curl -fsSL https://nginx.org/keys/nginx_signing.key | apt-key add -"
  become: yes
- name: update
  apt:
      update_cache: yes
  become: yes
  tags: update
- name: upgrade
  apt:
      upgrade: yes
  become: yes
  tags: update
- name: upgrade dist
  apt:
      upgrade: dist
  become: yes
  tags: update
- name: use apt to install nginx
  apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
  vars:
      packages:
          - nginx
  become: yes
  tags: install
- name: start NGINX
  shell: "{{ item }}"
  loop:
      - systemctl stop nginx.service
      - systemctl start nginx.service
      - systemctl enable nginx.service
  become: yes

  #sudo apt install curl gnupg2 ca-certificates lsb-release
  #echo "deb http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" | sudo tee /etc/apt/sources.list.d/nginx.list
  #curl -fsSL https://nginx.org/keys/nginx_signing.key | sudo apt-key add -
  #sudo apt update
  #sudo apt install nginx
  #
